package main

const MATTERMOST_USER_COOKIE = "MMUSERID"

const ONLYOFFICE_RC4_KEY string = "ONLYOFFICE"
const ONLYOFFICE_AUTHORIZATION_USERID_HEADER = "ONLYOFFICE_USER_ID"
const ONLYOFFICE_AUTHORIZATION_USERNAME_HEADER = "ONLYOFFICE_USERNAME"
const ONLYOFFICE_FILEVALIDATION_POSTID_HEADER = "ONLYOFFICE_POSTID"

const ONLYOFFICE_LOGGER_PREFIX = "[ONLYOFFICE]: "
const ONLYOFFICE_BOT_LOGGER_PREFIX = "[ONLYOFFICE_BOT]: "

const ONLYOFFICE_COMMAND_SERVICE string = "coauthoring/CommandService.ashx"
const ONLYOFFICE_API_JS string = "web-apps/apps/api/documents/api.js"
const ONLYOFFICE_CONVERTER string = ""

const ONLYOFFICE_PERMISSIONS_PROP = "ONLYOFFICE_PERMISSIONS"
const ONLYOFFICE_PERMISSIONS_WILDCARD_KEY = "*"

const ONLYOFFICE_API_PATH = "plugins/com.onlyoffice.mattermost-plugin/onlyofficeapi"
