package main

const MATTERMOST_USER_COOKIE = "MMUSERID"

const ONLYOFFICE_AUTHORIZATION_USERID_HEADER = "ONLYOFFICE_USER_ID"
const ONLYOFFICE_AUTHORIZATION_USERNAME_HEADER = "ONLYOFFICE_USERNAME"
const ONLYOFFICE_FILEVALIDATION_FILEID_HEADER = "ONLYOFFICE_FILEID"
const ONLYOFFICE_FILEVALIDATION_POSTID_HEADER = "ONLYOFFICE_POSTID"
const ONYLOFFICE_CHANNELVALIDATION_CHANNELID_HEADER = "ONLYOFFICE_CHANNELID"

const ONLYOFFICE_LOGGER_PREFIX = "[ONLYOFFICE]: "
const ONLYOFFICE_BOT_LOGGER_PREFIX = "[ONLYOFFICE_BOT]: "

const ONLYOFFICE_COMMAND_SERVICE string = "coauthoring/CommandService.ashx"
const ONLYOFFICE_API_JS string = "web-apps/apps/api/documents/api.js"
const ONLYOFFICE_CONVERTER string = ""

const ONLYOFFICE_API_PATH = "plugins/com.onlyoffice.mattermost-plugin/onlyofficeapi"

const ONLYOFFICE_ROUTE_EDITOR = "/editor"
const ONLYOFFICE_ROUTE_DOWNLOAD = "/download"
const ONLYOFFICE_ROUTE_CALLBACK = "/callback"
const ONLYOFFICE_ROUTE_SET_PERMISSIONS = "/set_file_permissions"
const ONLYOFFICE_ROUTE_GET_PERMISSIONS = "/get_file_permissions"
const ONLYOFFICE_ROUTE_GET_CHANNEL_USERS = "/channel_users"
