package utils

const ONLYOFFICE_LOGGER_PREFIX = "[ONLYOFFICE Utils]: "

const ONLYOFFICE_DOCUMENT_TYPE string = "word"
const ONLYOFFICE_SPREADSHEET_TYPE string = "cell"
const ONLYOFFICE_PRESENTATION_TYPE string = "slide"

var ONLYOFFICE_EXTENSION_TYPE_MAP map[string]string = map[string]string{
	"xls":  ONLYOFFICE_SPREADSHEET_TYPE,
	"xlsx": ONLYOFFICE_SPREADSHEET_TYPE,
	"xlsm": ONLYOFFICE_SPREADSHEET_TYPE,
	"xlt":  ONLYOFFICE_SPREADSHEET_TYPE,
	"xltx": ONLYOFFICE_SPREADSHEET_TYPE,
	"xltm": ONLYOFFICE_SPREADSHEET_TYPE,
	"ods":  ONLYOFFICE_SPREADSHEET_TYPE,
	"fods": ONLYOFFICE_SPREADSHEET_TYPE,
	"ots":  ONLYOFFICE_SPREADSHEET_TYPE,
	"csv":  ONLYOFFICE_SPREADSHEET_TYPE,
	"pps":  ONLYOFFICE_PRESENTATION_TYPE,
	"ppsx": ONLYOFFICE_PRESENTATION_TYPE,
	"ppsm": ONLYOFFICE_PRESENTATION_TYPE,
	"ppt":  ONLYOFFICE_PRESENTATION_TYPE,
	"pptx": ONLYOFFICE_PRESENTATION_TYPE,
	"pptm": ONLYOFFICE_PRESENTATION_TYPE,
	"pot":  ONLYOFFICE_PRESENTATION_TYPE,
	"potx": ONLYOFFICE_PRESENTATION_TYPE,
	"potm": ONLYOFFICE_PRESENTATION_TYPE,
	"odp":  ONLYOFFICE_PRESENTATION_TYPE,
	"fodp": ONLYOFFICE_PRESENTATION_TYPE,
	"otp":  ONLYOFFICE_PRESENTATION_TYPE,
	"doc":  ONLYOFFICE_DOCUMENT_TYPE,
	"docx": ONLYOFFICE_DOCUMENT_TYPE,
	"docm": ONLYOFFICE_DOCUMENT_TYPE,
	"dot":  ONLYOFFICE_DOCUMENT_TYPE,
	"dotx": ONLYOFFICE_DOCUMENT_TYPE,
	"dotm": ONLYOFFICE_DOCUMENT_TYPE,
	"odt":  ONLYOFFICE_DOCUMENT_TYPE,
	"fodt": ONLYOFFICE_DOCUMENT_TYPE,
	"ott":  ONLYOFFICE_DOCUMENT_TYPE,
	"rtf":  ONLYOFFICE_DOCUMENT_TYPE,
	"txt":  ONLYOFFICE_DOCUMENT_TYPE,
	"html": ONLYOFFICE_DOCUMENT_TYPE,
	"htm":  ONLYOFFICE_DOCUMENT_TYPE,
	"mht":  ONLYOFFICE_DOCUMENT_TYPE,
	"pdf":  ONLYOFFICE_DOCUMENT_TYPE,
	"djvu": ONLYOFFICE_DOCUMENT_TYPE,
	"fb2":  ONLYOFFICE_DOCUMENT_TYPE,
	"epub": ONLYOFFICE_DOCUMENT_TYPE,
	"xps":  ONLYOFFICE_DOCUMENT_TYPE,
}
